-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 10:22:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema learning
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `learning` ;

-- -----------------------------------------------------
-- Schema learning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learning` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `learning` ;

-- -----------------------------------------------------
-- Table `learning`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `learning`.`user` ;

CREATE TABLE IF NOT EXISTS `learning`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `email` VARCHAR(1000) NOT NULL,
  `level` INT NOT NULL DEFAULT '1' comment '1:使用者 2:教師 3:管理員',
  `authType` ENUM('local', 'github', 'google') NULL DEFAULT 'local',
  `authId` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE(`username`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `learning`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `learning`.`cart` ;

CREATE TABLE IF NOT EXISTS `learning`.`cart` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `isCheckOut` INT NOT NULL DEFAULT 0 comment '0:未購買 1:已購買',
  `checkOutTime` DATETIME NULL,
  PRIMARY KEY (`cartId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `cart_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `learning`.`user` (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `learning`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `learning`.`type` ;

CREATE TABLE IF NOT EXISTS `learning`.`type` (
  `typeId` INT NOT NULL AUTO_INCREMENT,
  `typeName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`typeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learning`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `learning`.`course` ;

CREATE TABLE IF NOT EXISTS `learning`.`course` (
  `courseId` INT NOT NULL AUTO_INCREMENT,
  `courseName` VARCHAR(50) NOT NULL,
  `courseDescription` VARCHAR(1000) NOT NULL,
  `courseDetail` VARCHAR(4000) NOT NULL,
  `courseImg` VARCHAR(1000) NOT NULL,
  `teacher` INT NOT NULL,
  `price` INT NOT NULL default 0,
  `typeId` INT NOT NULL,
  `createTime` DATETIME NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`courseId`),
  INDEX `course_teacher_idx` (`teacher` ASC) VISIBLE,
  INDEX `course_typeId_idx` (`typeId` ASC) VISIBLE,
  CONSTRAINT `course_teacher`
    FOREIGN KEY (`teacher`)
    REFERENCES `learning`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_typeId`
    FOREIGN KEY (`typeId`)
    REFERENCES `learning`.`type` (`typeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `learning`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `learning`.`resource` ;

CREATE TABLE IF NOT EXISTS `learning`.`resource` (
  `resourceId` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NOT NULL,
  `link` VARCHAR(1000) NOT NULL,
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` INT NOT NULL comment '1:影片 2:文檔 3: 試看影片',
  PRIMARY KEY (`resourceId`),
  INDEX `resource_courseId_idx` (`courseId` ASC) VISIBLE,
  CONSTRAINT `resource_courseId`
    FOREIGN KEY (`courseId`)
    REFERENCES `learning`.`course` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learning`.`cartItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `learning`.`cartItem` ;

CREATE TABLE IF NOT EXISTS `learning`.`cartItem` (
  `cartItemId` INT NOT NULL AUTO_INCREMENT,
  `cartId` INT NOT NULL,
  `courseId` INT NOT NULL,
  `price` INT NOT NULL default 0,
  `qty` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cartItemId`),
  INDEX `cartItem_cartId_idx` (`cartId` ASC) VISIBLE,
  INDEX `cartItem_courseId_idx` (`courseId` ASC) VISIBLE,
  CONSTRAINT `cartItem_cartId`
    FOREIGN KEY (`cartId`)
    REFERENCES `learning`.`cart` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartItem_courseId`
    FOREIGN KEY (`courseId`)
    REFERENCES `learning`.`course` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
